name: 'Set repository up, with a NodeJS environment'
description: |
  Checks out repository and sets NodeJS up with cached global and local dependencies
inputs:
  node-version:
    description: 'NodeJS version'
    required: true
outputs:
  has-local-cache:
    description: 'Was cache found'
    value: ${{ steps.restore-cached-dependencies.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - id: restore-cached-dependencies
      name: Restore cached dependencies
      uses: actions/cache@v4
      with:
        path: ./node_modules/
        key: ${{ runner.os }}-install-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-install-${{ inputs.node-version }}-
          ${{ runner.os }}-install-
    - name: Install dependencies
      shell: bash
      run: npm install
